tasty-coffee:
  user-name: some@mail.org
  password: very_long_secure_password

telegram-bot:
  token: 0000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  name: "@YourBot"

spring:
  datasource:
    username: postgres
    password: postgres