version: '3'

services:
  tastycoffee:
    container_name: tastycoffee
    environment:
      - TZ=Europe/Samara
    ports:
      - "8080:8080"
    build:
      context: .
    depends_on:
      - cache
      - rabbitmq
    volumes:
      - ./data/report:/report

  cache:
    container_name: redis
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./data/cache:/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres:
#  tastycoffee:
  cache:
