version: '3'

services:
  tastycoffee:
    container_name: tastycoffee
    ports:
      - "8080:8080"
    build:
      context: .
    depends_on:
      - db
      - cache
      - rabbitmq
    volumes:
      - ./data/report:/report

  db:
    image: 'postgres:14-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tastycoffee
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  cache:
    container_name: redis
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./data/cache:/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres:
  tastycoffee:
  cache:
