tasty-coffee:
  url: https://tastycoffee.ru

spring:
  config:
#    docker public
#     import: properties/db/db-docker.yml, properties/cache/cache-docker.yml, properties/secrets.yml, properties/mq/rabbitmq-docker.yml

#    docker dev
#     import: properties/db/db-docker.yml, properties/cache/cache-docker.yml, properties/secrets-dev.yml, properties/mq/rabbitmq-docker.yml

#    docker prod
#   import: properties/db/db-docker.yml, properties/cache/cache-docker.yml, properties/secrets-prod.yml, properties/mq/rabbitmq-docker.yml

#    local prod
#    import: properties/db/db-local-prod.yml, properties/cache/cache-local.yml, properties/secrets-prod.yml properties/mq/rabbitmq-local.yml

#    local dev
#    import: properties/db/db-local-dev.yml, properties/cache/cache-local.yml, properties/secrets-dev.yml, properties/mq/rabbitmq-local.yml

#    remote db dev
     import: properties/db/db-remote-dev.yml, properties/cache/cache-local.yml, properties/secrets-dev.yml, properties/mq/rabbitmq-local.yml

#    remote db prod
#    import: properties/db/db-remote-prod.yml, properties/cache/cache-docker.yml, properties/secrets-prod.yml, properties/mq/rabbitmq-docker.yml


  jpa:
    generate-ddl: true
#    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: public